### ISSUE TITLE
Additional Feature for OhGodMusicBot

### ISSUE THREAD

**Issue by ge-em** [bdistin/ClanAlogPoster#52]
Hello, because i'am working on OhGodMusicBot project, and the project that i working on is archived, i am not able to do an pull request from your amazing bot. But i've some additional upgrade by adding some important feature in a music bot.
The feature are:
-Show What song is playing currently: this is important because some people that join the voice channel in the middle of the song might want to know the title of the song.
-Empty the queue: this function help to end the bot easier, just by making the queue empty, user does not need to skip all the song in the queue to play their song that they want next.
-Show the lyrics the current song
-Play the previous song: this is additional feature that might make the bot unique than other
If you are interested please accept my pull request
Thanks.

**Comment by Favna** [comment]
my reaction after reading this

![image](https://user-images.githubusercontent.com/4019718/73970791-0e8a1b80-491e-11ea-9961-c242390089d9.png)
